openmrs/openmrs-module-bedmanagement

- api/src/main/java/org/openmrs/module/bedmanagement/BedManagementDAO.java
- api/src/main/java/org/openmrs/module/bedmanagement/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/BedManagementServiceImpl.java
- api/src/main/java/org/openmrs/module/bedmanagement/HibernateBedManagementDAO.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceIntegrationTest.java
- api/src/test/java/org/openmrs/module/bedmanagement/HibernateBedManagementDAOTest.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResourceSearchHandler.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResourceSearchHandlerTest.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/MainResourceControllerTest.java
- omod/src/test/resources/TestingApplicationContext.xml
- omod/src/test/resources/bedManagementDAOComponentTestDataset.xml
- omod/src/test/resources/test-hibernate.cfg.xml
Created a new resource to fetch bed details by visit uuid.
> Padma, Jaswanth | #3114 | Resource to fetch bed details by visit

- api/src/main/java/org/openmrs/module/bedmanagement/BedManagementService.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceTest.java
- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
This is the new pull request, please ignore the privious one.
> Padma, Santhosh | Adding privileges and authorization

- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResourceSearchHandler.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedPatientAssignmentResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedResource.java
Added 2.1.* in all resources to supportedOpenmrsVersions
> BED-1 Upgrade openmrs version in all resources to support 2.1.*

- api/src/main/java/org/openmrs/module/bedmanagement/BedLayout.java
- api/src/main/java/org/openmrs/module/bedmanagement/BedLayoutWithDetails.java
- Add bedUuid property in bed layout
- Check null pointer before setting value
Please code review @mks-d
> BAH-325 Add bedUuid property and check null pointer

- api/src/main/java/org/openmrs/module/bedmanagement/dao/BedManagementDao.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/impl/BedManagementDaoImpl.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceTest.java
- api/src/test/java/org/openmrs/module/bedmanagement/HibernateBedManagementDaoTest.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedResourceTest.java
- omod/src/test/resources/bedManagementDAOComponentTestDataset.xml
> BAH-325 Extend Bed REST Resource

- api/src/main/java/org/openmrs/module/bedmanagement/dao/BedManagementDao.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/impl/BedManagementDaoImpl.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceTest.java
- api/src/test/java/org/openmrs/module/bedmanagement/HibernateBedManagementDaoTest.java
- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTagResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedTagResourceTest.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResourceTest.java
[BAH-325](https://bahmni.atlassian.net/browse/BAH-325) Extend REST API for ward/bed management
@mks-d Please code review.
> BAH-325 Extend Bed Tag REST Resource

- omod/pom.xml
- omod/src/main/resources/config.xml
- owa/.gitignore
- owa/README.md
- owa/assembly.xml
- owa/pom.xml
- pom.xml
[BAH-413](https://bahmni.atlassian.net/browse/BAH-413): Enable auto deploy OWA app on deploying Bed Management module.
@mks-d Please code review.
> BAH-413 configure automatically deploy owa on installing bed management omod

- owa/.prettierrc.js
- owa/README.md
- owa/package.json
[BAH-416](https://bahmni.atlassian.net/browse/BAH-416): Code formatting upon building
This pull request only contains setup prettier code formatter for js. Formatted codes will be push and raise PR after this pull request merged.
Please code review.
@mks-d
> BAH-416 setup prettier code formatter for js

- api/src/main/resources/messages.properties
- omod/pom.xml
- omod/src/main/java/org/openmrs/module/bedmanagement/extension/html/AdminList.java
- omod/src/main/resources/config.xml
- pom.xml
[BAH-436](https://bahmni.atlassian.net/browse/BAH-436): Link to the new admin page from the legacy admin UI
Please code review.
@mks-d
> BAH-436 Add link to the admin page from the legacy admin UI

- api/src/main/java/org/openmrs/module/bedmanagement/dao/BedManagementDao.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/impl/BedManagementDaoImpl.java
- api/src/main/java/org/openmrs/module/bedmanagement/entity/BedType.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/main/resources/BedType.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/bedmanagement/HibernateBedManagementDaoTest.java
- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
- api/src/test/resources/bedTagMapTestDataSet.xml
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResourceTest.java
- omod/src/test/resources/bedManagementDAOComponentTestDataset.xml
- owa/app/components/__mocks__/bedTypeFunctions-mock.js
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/__snapshots__/addEditBed-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/addEditBed-test.js
- owa/app/components/__tests__/bedType/__snapshots__/bedTypeListing-test.js.snap
- owa/app/components/__tests__/bedType/__snapshots__/bedTypeWrapper-test.js.snap
- owa/app/components/__tests__/bedType/__snapshots__/listRow-test.js.snap
- owa/app/components/__tests__/bedType/addEditBedType-test.js
- owa/app/components/__tests__/bedType/bedTypeWrapper-test.js
- owa/app/components/__tests__/bedType/listRow-test.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/addEditBed.js
- owa/app/components/bedType/bedTypeForm/addEditBedType.js
- owa/app/components/bedType/bedTypeList/bedTypelistRow.js
- owa/app/components/bedType/bedTypeWrapper.js
- owa/app/utilities/__tests__/testData.json
[BAH-443](https://bahmni.atlassian.net/browse/BAH-443): Bed Management to comply with OpenMRS metadata data model
Please code review. @mks-d
> BAH-443 extend BedType entity with BaseOpenmrsMetadata

- api/src/main/java/org/openmrs/module/bedmanagement/BedManagementActivator.java
- api/src/main/java/org/openmrs/module/bedmanagement/constants/BedManagementProperties.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/BedManagementDao.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/impl/BedManagementDaoImpl.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceTest.java
- api/src/test/java/org/openmrs/module/bedmanagement/HibernateBedManagementDaoTest.java
- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/bedmanagement/extension/html/AdminList.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResource.java
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/__snapshots__/setLayout-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/bedLayout/__snapshots__/bedLayout-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/bedLayout/bedLayout-test.js
- owa/app/components/admissionLocation/admissionLocationWrapper.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/addEditAdmissionLocation.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/addEditBed.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/admissionLocationForm.css
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/setBedLayout.js
- owa/app/components/admissionLocation/rightPanel/bedLayout/bedBlock.js
- owa/app/components/admissionLocation/rightPanel/bedLayout/bedlayout.css
- owa/app/components/admissionLocation/rightPanel/bedLayout/index.js
- owa/app/components/admissionLocation/rightPanel/locationBlock/index.js
- owa/app/components/bedTag/bedTagForm/addEditBedTag.js
- owa/app/components/bedTag/bedTagList/bedTagListRow.js
- owa/app/components/bedTag/bedTagWrapper.js
- owa/app/components/bedType/bedTypeForm/addEditBedType.js
- owa/app/components/bedType/bedTypeList/bedTypelistRow.js
- owa/app/components/bedType/bedTypeWrapper.js
- owa/app/css/notify.css
[BAH-438](https://bahmni.atlassian.net/browse/BAH-438): Should be able to resize bed layout size.
Please code review.
@mks-d
> BAH-438 Enable resize bed layout size feature

- .travis.yml
- api/src/main/java/org/openmrs/module/bedmanagement/atomfeed/BedAssignmentAdvice.java
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/__snapshots__/setLayout-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/setLayout-test.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/setBedLayout.js
- owa/package.json
- owa/pom.xml
- pom.xml
[BAH-451](https://bahmni.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=BAH-451)
Patients assign not working on Bahmni 0.90 due to the event publisher failure issue resolved in this PR.
Please code review. @mks-d
> BAH-451 resolve event publisher issue

- owa/app/utilities/localeHelper.js
BAH-412: Implement internationalization (I18N) in Bed Management UI
ReOpen with resolving Travis-CI build fail issue.
Please code review @mks-d
> BAH-412 Setup i18n for owa UI

- owa/app/components/app.js
- owa/app/index.js
- owa/app/utilities/localeHelper.js
[BAH-486](https://bahmni.atlassian.net/browse/BAH-486): Avoid hardcoding of default locale & allowed-locales in Bed Management Admin UI App.
@mks-d  Please code review.
> BAH-486 avoid hard coding of locale info

- api/src/main/resources/messages.properties
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResourceTest.java
- omod/src/test/resources/removeAdmissionLocationTagTestDataset.xml
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/__snapshots__/addEditAdmissionLocation-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/__snapshots__/addEditBed-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationForm/addEditBed-test.js
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationList/__snapshots__/admissionLocationList-test.js.snap
- owa/app/components/__tests__/admissionLocation/rightPanel/admissionLocationList/admissionLocationList-test.js
- owa/app/components/__tests__/admissionLocation/rightPanel/bedLayout/__snapshots__/bedBlock-test.js.snap
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/addEditAdmissionLocation.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationForm/addEditBed.js
- owa/app/components/admissionLocation/rightPanel/admissionLocationList/index.js
- owa/app/components/admissionLocation/rightPanel/bedLayout/bedBlock.js
- owa/app/components/admissionLocation/rightPanel/bedLayout/bedlayout.css
- owa/app/i18n/messages.js
Improve title in OpenMRS admin screen
Show a slightly clearer error message if you try to create an Admission Location without having an AdmissionLocation tag
Adding a top-level ward should say "Add Admission Location" instead of "Add Ward"
Adding a bed should show an error message if you haven't configured any bed types yet
When adding beds, existing beds should be a different color than empty slots
> BAH-313 - various fixes

- api/src/main/java/org/openmrs/module/bedmanagement/exception/BedOccupiedException.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceTest.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedResourceTest.java
- owa/app/components/admissionLocation/admissionLocationWrapper.js
- owa/app/components/admissionLocation/rightPanel/bedLayout/bedBlock.js
- owa/app/i18n/messages.js
I don't have a test for the react code not deleting an occupied bed, because I got stuck trying to deal with mocking axios behind the scenes. But this did work in real life.
> BAH-527 Do not allow a bed to be deleted if it is occupied

- api/src/main/java/org/openmrs/module/bedmanagement/atomfeed/BedTagMapAdvice.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/bedmanagement/atomfeed/BedTagMapAdviceTest.java
- omod/src/main/resources/config.xml
- pom.xml
https://bahmni.atlassian.net/browse/BAH-598
> BAH-598: Add bedTagMap advice to record events

- api/src/main/resources/liquibase.xml
Fix SQL Precondition for changeSet adding foreign key on bed_location_map.bed_id
> Fix SQL Precondition in of ChangeSet 201807050219

- api/src/main/resources/liquibase.xml
This pull request is a fix for [BAH-661](https://bahmni.atlassian.net/browse/BAH-661). This will fix the error which occurs while creating new bed layout.
> BAH-661 | Drop not null constraint for bed_id in bed_location map table.

- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/BedTagMapService.java
- api/src/main/resources/liquibase.xml
- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
- api/src/test/resources/bedTagMapTestDataSet.xml
BAH-664 | Introduced missing privileges (Edit Beds,Edit Bed Type,Get Bed Type) and renamed privileges (Edit Tags, Get Tags) to (Edit Bed Tags, Get Bed Tags). Updated Test Data
> BAH-664 | Introduced missing privileges and renamed privileges Get Tags, Edit Tags to Get Bed Tags, Edit Bed Tags respectively.

- .travis.yml
Fixed by switching to OpenJDK 8
> Travis build to use OpenJDK 8.

- api/src/test/resources/bedManagementDAOComponentTestDataset.xml
- omod/src/test/resources/bedManagementDAOComponentTestDataset.xml
https://bahmni.atlassian.net/browse/BAH-3230
Amendment to PR https://github.com/openmrs/openmrs-module-bedmanagement/pull/60
> BAH-3230 Change test data to match the column changes made on column_number and row_number

- api/src/main/java/org/openmrs/module/bedmanagement/BedLayout.java
- api/src/main/java/org/openmrs/module/bedmanagement/dao/impl/BedManagementDaoImpl.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResource.java
See:  https://openmrs.atlassian.net/browse/BED-13
> BED-13: Include bed assignment encounter in /admissionLocation response

- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResource.java
See:  https://openmrs.atlassian.net/browse/BED-12
> BED-12 - bedtype endpoint should should support custom representation

- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/AdmissionLocationResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedDetailsResourceSearchHandler.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTagResource.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResource.java
See:  https://openmrs.atlassian.net/browse/BED-15
> BED-15 - Rest resources should support OpenMRS paging standards

- api/src/main/resources/liquibase.xml
Ticket: https://openmrs.atlassian.net/browse/O3-4492
> O3-4492: O3-4492: Resolve errors when running with PostgreSQL

- api/src/main/java/org/openmrs/module/bedmanagement/service/BedManagementService.java
- api/src/main/java/org/openmrs/module/bedmanagement/service/impl/BedManagementServiceImpl.java
- api/src/test/java/org/openmrs/module/bedmanagement/BedManagementServiceImplTest.java
- omod/src/main/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResource.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedTagMapResourceTest.java
- omod/src/test/java/org/openmrs/module/bedmanagement/rest/resource/BedTypeResourceTest.java
- omod/src/test/resources/bedManagementDAOComponentTestDataset.xml
Ticket: https://bahmni.atlassian.net/browse/BAH-4197
> BAH-4197: Bed Management REST API allow bed types to be retired
